package com.app.tradingplatform.domain;

// Generated Apr 25, 2014 11:56:33 PM by Hibernate Tools 3.4.0.CR1

/**
 * User generated by hbm2java
 */
public class User implements java.io.Serializable {

	private int userId;
	private String lastName;
	private String firstName;
	private String address;
	private String city;

	public User() {
	}

	public User(int userId) {
		this.userId = userId;
	}

	public User(int userId, String lastName, String firstName, String address,
			String city) {
		this.userId = userId;
		this.lastName = lastName;
		this.firstName = firstName;
		this.address = address;
		this.city = city;
	}

	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

}
